### ISSUE TITLE
Charles not recording/tracking/showing anything or working in OSX using Chrome browser.

### ISSUE THREAD

**Issue by leedium** [leedium/occ-react-component#49]
I have run into this issue countless times, and here are my steps. It's most likely due to the fact that most sites are HTTPS and and maybe only proxy by HTTP is enabled.

**Comment by leedium** [comment]
1.  In Charles >Help>SSL Proxying>Install Charles Root Certificate
2. Double Click on the red icon
3. Select "trust" and set to "Always Trust" save and confirm.
4. Go to OSX System Preferences>Network>Advanced>Proxies> 
Disable Auto Proxy Discover and Web Proxy (HTTP)
Disable (for now) WEB Proxy (HTTP)
Enable Secure Web Proxy (HTTPS)
5. In Charles >Tools>macOS Proxy> and set to enable.
6. In Charles >Tools>No Caching> and set to enable.
7. Open up Chrome dev tools >Network> enable "Disable Cache"
8. ALWAYS keep the chrome dev tools open when you proxy.  For some reason it doesn't work without the window open.
9.  Refresh the page.
10. If you see the requests, select the server, right click, and select "Enable SSL Proxying"
11.  Refresh the page, and you should be able to inspect the requests.

That's it.

Hopefully this helps.

Cheers!

**Comment by mrswd32** [comment]
what if it gives an error:
Unable to import “Charles Proxy Custom Root Certificate (built on EMODO-PQ05F, 11 Apr 2022)”.

Error: -25294

**Comment by 0res7** [comment]
its better if you can add a screenshot for Error: -25294
