### ISSUE TITLE
dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by ermarin** [leedium/occ-react-component#64]
Hello, i'm using occ and i would create new components with React.js. I follow this example but when i run 'npm run dev' in console returner this warning and the app not finish run. I use windows. Someone help me please, regards :)

![console](https://user-images.githubusercontent.com/8620255/56242174-448fa380-605d-11e9-9098-4d1856b8ade1.jpg)
![console](https://user-images.githubusercontent.com/8620255/56242199-5a9d6400-605d-11e9-86e0-a1d1c5c6a7ef.jpg)

**Comment by leedium** [comment]
Hey emarin, that is the linter telling you "not to use" that property.  You can disable that in your `eslintrc.json`.  So try something like this:
```
{
  "rules": {
    "react/no-danger": 0
  }
}
```

**Comment by ermarin** [comment]
It worked, thanks :D
